### ISSUE TITLE
Can't compile under linux

### ISSUE THREAD

**Issue by emdio** [LeviGibson/eggnog-chess-engine#2]
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

After cloning the repo and running "make all" I get the next messages:

$ make all
make avx2 && make avx && make sse && make sse2 && make popcnt
make[1]: Entering directory '/home/emilio/soft/git/eggnog'
gcc -O3 -pthread -DAVX2 -mavx2 main.c syzygy.c bitboard.c board.c perft.c uci.c search.c timeman.c transposition.c moveOrder.c Fathom/*.c moveOrderData.c nnue/nnue.c -o ./bin/eggnog-chess-engine-avx2-linux
make[1]: Leaving directory '/home/emilio/soft/git/eggnog'
make[1]: Entering directory '/home/emilio/soft/git/eggnog'
gcc -O3 -pthread -DAVX -mavx main.c syzygy.c bitboard.c board.c perft.c uci.c search.c timeman.c transposition.c moveOrder.c Fathom/*.c moveOrderData.c nnue/nnue.c -o ./bin/eggnog-chess-engine-avx-linux
nnue/nnue.c: In function ‘load_model’:
nnue/nnue.c:49:5: error: unknown type name ‘FILE’
   49 |     FILE *fin = fopen(path, "rb");
      |     ^~~~
nnue/nnue.c:6:1: note: ‘FILE’ is defined in header ‘<stdio.h>’; did you forget to ‘#include <stdio.h>’?
    5 | #include "../transposition.h"
  +++ |+#include <stdio.h>
    6 | #include <string.h>
nnue/nnue.c:49:17: warning: implicit declaration of function ‘fopen’ [-Wimplicit-function-declaration]
   49 |     FILE *fin = fopen(path, "rb");
      |                 ^~~~~
nnue/nnue.c:49:17: note: ‘fopen’ is defined in header ‘<stdio.h>’; did you forget to ‘#include <stdio.h>’?
nnue/nnue.c:49:17: warning: initialization of ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
nnue/nnue.c:52:5: warning: implicit declaration of function ‘fseek’ [-Wimplicit-function-declaration]
   52 |     fseek(fin, TRANSFORMERSTART, SEEK_SET);
      |     ^~~~~
nnue/nnue.c:52:34: error: ‘SEEK_SET’ undeclared (first use in this function)
   52 |     fseek(fin, TRANSFORMERSTART, SEEK_SET);
      |                                  ^~~~~~~~
nnue/nnue.c:52:34: note: each undeclared identifier is reported only once for each function it appears in
nnue/nnue.c:53:11: warning: implicit declaration of function ‘fread’ [-Wimplicit-function-declaration]
   53 |     tmp = fread(in_biases, sizeof(int16_t), KPSIZE, fin);
      |           ^~~~~
nnue/nnue.c:56:19: error: ‘SEEK_CUR’ undeclared (first use in this function)
   56 |     fseek(fin, 4, SEEK_CUR);
      |                   ^~~~~~~~
nnue/nnue.c:73:5: warning: implicit declaration of function ‘fclose’ [-Wimplicit-function-declaration]
   73 |     fclose(fin);
      |     ^~~~~~
make[1]: *** [Makefile:26: avx] Error 1
make[1]: Leaving directory '/home/emilio/soft/git/eggnog'
make: *** [Makefile:20: all] Error 2

**Comment by LeviGibson** [comment]
This is solved. Thanks!
Just clone and again and it should be fine.
