### ISSUE TITLE
Engine installs itself as Levi Gibson instead of EggNog

### ISSUE THREAD

**Issue by GrahamCCRL** [LeviGibson/eggnog-chess-engine#4]
As you've seen in my Division 7 tournament. :-)

**Comment by LeviGibson** [comment]
Thanks for letting me know!
This has been fixed.
https://github.com/LeviGibson/eggnog-chess-engine/commit/f4743c9d9c5aa0e7b392e901534082659c370eed

**Comment by GrahamCCRL** [comment]
For CCRL engine details, what is your nationality?

**Comment by LeviGibson** [comment]
I'm from the United States.
If you want you can clone again and build with `make avx2`. It has the fixed UCI bug and a newer network.

**Comment by GrahamCCRL** [comment]
Thanks.
I'll wait for an exe. :-)

**Comment by LeviGibson** [comment]
Wonderful.
I just uploaded a new build.
https://drive.google.com/drive/folders/1yP7r3Fs02oNrWU0Uen2EErcsgMfuemdj?usp=sharing

**Comment by GrahamCCRL** [comment]
Thanks for that. :-)
